version: "3.9"

services:
  db:
    image: mysql:8.4
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: IsturgiRoot_2026_DB94
      MYSQL_DATABASE: tenis_isturgi
      MYSQL_USER: tenis_user
      MYSQL_PASSWORD: IsturgiApp_2026_User57
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./spring-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: tenis_isturgi
      DB_USER: tenis_user
      DB_PASSWORD: IsturgiApp_2026_User57

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://ystmqi9daf5g8za4avnliezn.51.210.104.106.sslip.io
        VITE_FIREBASE_API_KEY: AIzaSyBxsLRoR_7obGhweEWhaW43XVNH9PMYJfA
        VITE_FIREBASE_AUTH_DOMAIN: tenis-isturgi.firebaseapp.com
        VITE_FIREBASE_PROJECT_ID: tenis-isturgi
        VITE_FIREBASE_STORAGE_BUCKET: tenis-isturgi.firebasestorage.app
        VITE_FIREBASE_MESSAGING_SENDER_ID: 707348941864
        VITE_FIREBASE_APP_ID: 1:707348941864:web:d54fcecfb0677a6851791d
        VITE_ADMIN_EMAILS: admin@isturgi.com
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  mysql_data:
